### ISSUE TITLE
a, b, c, d of boost::math::quaternion are no longer public

### ISSUE THREAD

**Issue by biochem-fan** [CueMol/cuemol2#190]
Instead,  `R_component_1()`,  `R_component_2()`, ... should be used.

http://www.boost.org/doc/libs/1_66_0/libs/math/doc/html/math_toolkit/quat_mem_fun.html#math_toolkit.quat_mem_fun.individual_real_components

**Comment by ishitani** [comment]
The R_component_n() methods are const, so it is not easy to modify the BALL's quaterion impl to use only these methods. Instead, I made a local copy of ver 1.64's boost/math/quaternion.hpp in the repository, changed the namespace, and modified the BALL's quaternion impl to use it. I checked that the mol surface generation works without apparent problems.
