### ISSUE TITLE
Bug Hunting – Cuemol2: Molecular Visualization Framework, Changing Cell Dimension Symmetry cause the program does not respond and then Cuemol2.exe stops working !

### ISSUE THREAD

**Issue by emirfirlar** [CueMol/cuemol2#194]
![Ekran Alıntısı1.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521547170/krzbyynhsnx5mzqneatc.jpg)

&emsp;

#### <h1>Expected behavior</h1>

&emsp;

<h3> Changing Cell Dimension Symmetry </h3>

&emsp;

#### <h1>Actual behavior</h1>

&emsp;

<h3>The program does not respond and then Cuemol2.exe stops working</h3>

&emsp;

#### <h1>How to reproduce</h1>

&emsp;

&nbsp;&nbsp;&nbsp; I was using Cuemol2. I downloaded file by using PDB feature. I did 200 Angström by using Symm Mol feature. Then i clicked Change Symmetry. I made change in Cell Dimension. I wrote 0.52 instead of 95.52. When i clicked to ok button, Cuemol2.exe does not respond and then Cuemol2.exe stops working !

&emsp;

&nbsp;&nbsp;&nbsp; I am following this process while making this error:

&emsp;

* Get PDB usin accession code.. – Enter PDB ID: 1FN3 – Ok (Download PDB window) – Ok (Setup Renderer) – Symm Mol – 200 Angström – Change Symmetry – a=0.52 instead of 95.52 in Cell Dimension – Ok – Cuemol2 does not respond - Cuemol2.exe stops working

&emsp;

&nbsp;&nbsp;&nbsp;This bug causes the program to stop working and shutdown itself, it should be fixed.

&emsp;

* Operating system 1: Windows 7 professional SP1 (32 bit)
İntel Core 2 Duo 2.13 Ghz , 4 gb RAM

* Program Version 1: Version 2.2.3.430 (32 bit)

&emsp;

#### <h1>Recording Of The Bug</h1>

&emsp;

* Change Symmetry a=0.52 instead of 95.52 in Cell Dimension Gif’s: 

&emsp;

<center>![gif.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521547323/fhqsb3uknfuuk8wa92ln.gif)
</center>

&emsp;

* You can see the error in the  video in detail below:

&emsp;

<iframe width="640" height="360" src="https://www.youtube.com/embed/2UfxcTuPLQ4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

&emsp;

Useful Links:

[Cuemol2]( http://www.cuemol.org/en/)

[Github Repository]( https://github.com/CueMol/cuemol2)

[Protein Data Bank]( https://www.rcsb.org/)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@emirfirlar/bug-hunting-cuemol2-molecular-visualization-framework-changing-cell-dimension-symmetry-cause-the-program-does-not-respond-and">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ishitani** [comment]
Changing the cell constant to 0.1 will results in too many symmetry operators generated within 200 angstroms. Such situation is abnormal, but possibly occurs by error of user input. To avoid this situation, I limited the number of symops generated in the symm renderer by "maxops" property of the symm renderer. The default value is 1000, which might be large enough for normal applications.

**Comment by emirfirlar** [comment]
thank you for informing.
