### ISSUE TITLE
Bug Hunting – Cuemol2: Molecular Visualization Framework, “APBS elepot calculation tool” feature “Max grid size” error !

### ISSUE THREAD

**Issue by emirfirlar** [CueMol/cuemol2#196]
![Ekran Alıntısı.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521579359/or7fk1eay2u1irftru9f.jpg)

&emsp;

#### <h1>Expected behavior</h1>

&emsp;

<h3> APBS Elepot Calculation </h3>

&emsp;

#### <h1>Actual behavior</h1>

&emsp;

<h3>APBS.exe Stops Working</h3>

&emsp;

#### <h1>How to reproduce</h1>

&emsp;

&nbsp;&nbsp;&nbsp; I loaded the file. Then i opened APBS elepot calculation. I did Max grid size option in APBS options. APBS elepot calculation tool gives error between 0.1 and 0.5 Angström. When i chose this values, APBS calculation tool gives error. Before, APBS.exe stops working. Then it gives error: APBS calculation failed ! This error doesn’t affect the operation of the program. Only it affects APBS tool. The program continues to work. This error is affecting to only APBS tool.

&emsp;

&nbsp;&nbsp;&nbsp; I am following this process while making this error:

&emsp;

* Get PDB usin accession code.. – Enter PDB ID: 1FN3 – Ok (Download PDB window) – Ok (Setup Renderer) – Tools – APBS elepot calculation – APBS Options – Max grid size – Change Angström value – Ok – APBS.exe stops working – Cancel – Error: APBS calculation failed 

&emsp;

&nbsp;&nbsp;&nbsp;This bug causes the APBS elepot calculation tool to stop working and shutdown tool itself, it should be fixed.

&emsp;

* Operating system 1: Windows 7 professional SP1 (32 bit)
İntel Core 2 Duo 2.13 Ghz , 4 gb RAM

* Program Version 1: Version 2.2.3.430 (32 bit)

&emsp;

#### <h1>Recording Of The Bug</h1>

&emsp;

* APBS Calculation Tool Gif’s: 

&emsp;

<center>https://media.giphy.com/media/2zoLcBABrGLivB0xSI/giphy.gif</center>

&emsp;

* You can see the error in the  video in detail below:

&emsp;

<iframe width="640" height="360" src="https://www.youtube.com/embed/xVZl7M94kEE" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

&emsp;

Useful Links:

[Cuemol2]( http://www.cuemol.org/en/)

[Github Repository]( https://github.com/CueMol/cuemol2)

[Protein Data Bank]( https://www.rcsb.org/)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@emirfirlar/bug-hunting-cuemol2-molecular-visualization-framework-apbs-elepot-calculation-tool-feature-max-grid-size-error">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ishitani** [comment]
This is not a bug, but an expected behavior. Changing the grid size to small values result in many grid points, which numerously increase the calculation costs (in the order of O(n^3)).

**Comment by emirfirlar** [comment]
thank you for informing

**Comment by emirfirlar** [comment]
i understand, thank you for informing
