### ISSUE TITLE
Bug Hunting – Cuemol2: Molecular Visualization Framework, “Interaction Analysis ”tool error !

### ISSUE THREAD

**Issue by emirfirlar** [CueMol/cuemol2#197]
![Ekran Alıntısı.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521746645/l04lhd9vcs24ko9me4fs.jpg)

&emsp;

#### <h1>Expected behavior</h1>

&emsp;

<h3> Interaction Analysis Calculation </h3>

&emsp;

#### <h1>Actual behavior</h1>

&emsp;

<h3> Interaction Analysis not Responding short-time </h3>

&emsp;

#### <h1>How to reproduce</h1>

&emsp;

&nbsp;&nbsp;&nbsp; I loaded the file. Then i opened Interaction Analysis. I changed Min Distance by 0.5. I changed Max Distance by 4.5. I changed Max labels by 1. Then i clikced to Ok button. When i clicked anywhere Interaction analysis tool didn’t respond short time. Then, it has responded and calculated. 

&emsp;

&nbsp;&nbsp;&nbsp; I am following this process while making this error:

&emsp;

* Get PDB usin accession code.. – Enter PDB ID: 1FN3 – Ok (Download PDB window) – Ok (Setup Renderer) – Tools – Interaction.. – Min Distance 0.5 – Max Distance 4.5 – Max Labels 1 – Ok – i clicked anywhere– Not Respond Short-Time – Responded to - Finished

&emsp;

&nbsp;&nbsp;&nbsp; This bug causes the Interaction Analysis tool stops working short time. If you force the program in the meantime, the program will crash. So it should be fixed.

&emsp;

* Operating system 1: Windows 7 professional SP1 (32 bit)
İntel Core 2 Duo 2.13 Ghz , 4 gb RAM

* Program Version 1: Version 2.2.3.430 (32 bit)

&emsp;

#### <h1>Recording Of The Bug</h1>

&emsp;

* Interaction Analysis Tool Gif’s: 

&emsp;

<center> ![2018_03_22_21_40_01_1280x768gif.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521746672/fsfvkddk2zgzj34ihal3.gif)
</center>

&emsp;

* You can see the error in the  video in detail below:

&emsp;

<iframe width="640" height="360" src="https://www.youtube.com/embed/0zjjQDL9QVk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

&emsp;

Useful Links:

[Cuemol2]( http://www.cuemol.org/en/)

[Github Repository]( https://github.com/CueMol/cuemol2)

[Protein Data Bank]( https://www.rcsb.org/)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@emirfirlar/bug-hunting-cuemol2-molecular-visualization-framework-interaction-analysis-tool-error">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ishitani** [comment]
This is not a bug, but an expected behavior. Interaction detection requires much time depending on the parameters.

**Comment by emirfirlar** [comment]
i understand, thank you for informing
